name: Build (Linux/GCC/Qt6)
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Ubuntu:
    runs-on: ubuntu-24.04
    steps:
    - name: Clone Tree
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          g++ cmake ninja-build \
          libocct-draw-dev libocct-visualization-dev libocct-ocaf-dev libocct-modeling-data-dev \
          libocct-modeling-algorithms-dev libocct-foundation-dev libocct-data-exchange-dev \
          libgl-dev libegl-dev \
          tcllib tklib tcl-dev tk-dev \
          libtbb-dev \
          qt6-base-dev qt6-declarative-dev qml6-module-qtquick-controls qml6-module-qtquick-templates \
          xvfb scrot
    - name: Configure project
      run: |
        mkdir "build"
        cmake -G Ninja -S . -B "./build" -D QT_VERSION=Qt6
    - name: Build project
      run: |
        cmake --build "./build" --config Release
    - name: Run tests
      run: |
        xvfb-run --server-args="-screen 0 800x600x24" ./.github/workflows/screenshot.sh ./build/occt-qwidget/occt-qwidget-sample             ./build/occt-qwidget.png       5
        xvfb-run --server-args="-screen 0 800x600x24" ./.github/workflows/screenshot.sh ./build/occt-qopenglwidget/occt-qopenglwidget-sample ./build/occt-qopenglwidget.png 5
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: occt-qwidget
        path: ./build/*.png
